### ISSUE TITLE
ChartFormat class is missing in  openbb_core.app.model.charts.chart with openbb version 4.3.0

### ISSUE THREAD

**Issue by bsakash137** [deeleeramone/RRG-Dashboard#2]
Hi,

Thanks for this implementation of RRG with openBB.

I am getting below error when I run it in Spyder after installing all openBB modules. Could you please provide some solution to this?

runfile('C:/Users/akash/Documents/RRG/streamlit_app.py', wdir='C:/Users/akash/Documents/RRG')
Traceback (most recent call last):

  File "C:\Users\akash\Documents\RRG\streamlit_app.py", line 55, in <module>
    module = import_from_file("module", "relative_rotation.py")

  File "C:\Users\akash\Documents\RRG\streamlit_app.py", line 52, in import_from_file
    spec.loader.exec_module(module)

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "relative_rotation.py", line 21, in <module>
    from openbb_core.app.model.charts.chart import Chart, ChartFormat

ImportError: cannot import name 'ChartFormat' from 'openbb_core.app.model.charts.chart' (C:\Users\akash\anaconda3\lib\site-packages\openbb_core\app\model\charts\chart.py)

Thanks,
Akash

**Comment by deeleeramone** [comment]
Hey, thanks a lot for flagging the issue. You are absolutely correct, this class is now just a simple dictionary and is no longer an importable item!

I've updated the broken syntax and then added explicit items to the `requirements.txt` file, and the redeployment appears to be working. Let me know if you find otherwise!
